database:
  host: localhost
  port: 5432
  database: metrics
  user: postgres
  password: password

timescale:
  chunk_interval: '1 day'
  retention_policy: '7 days'
  compression_enabled: true

batch_writer:
  batch_size: 1000
  flush_interval: 2.0  # seconds
  connection_pool_size: 10
