version: 1
formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
handlers:
  default:
    level: INFO
    formatter: standard
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file:
    level: DEBUG
    formatter: standard
    class: logging.FileHandler
    filename: 'logs/cost_allocation.log'
    mode: 'a'
root:
  level: DEBUG
  handlers: [default, file]
